import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'etter',
  description: 'Natural language geographic query parsing using LLMs',

  base: '/etter/',

  // /api/ is generated by pdoc at build time and does not exist as .md files
  ignoreDeadLinks: [/\/api\//],
  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { href: 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap', rel: 'stylesheet' }],
  ],

  themeConfig: {
    logo: '/etter-logo.png',
    siteTitle: 'etter',

    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'API Reference', link: '/api/etter.html' },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting Started', link: '/guide/getting-started' },
          { text: 'Spatial Relations', link: '/guide/spatial-relations' },
          { text: 'Datasources', link: '/guide/datasources' },
          { text: 'Error Handling', link: '/guide/error-handling' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'API Reference', link: '/api/etter.html' },
        ],
      },
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/geoblocks/etter' },
    ],

    footer: {
      message: 'Released under the BSD-3-Clause License.',
      copyright: 'Sponsored by <a href="https://www.camptocamp.com" target="_blank">Camptocamp</a>',
    },

    search: {
      provider: 'local',
    },
  },
})
